version: '2'
services:
  drupal-project-mysql:
    container_name: drupal-project-mysql
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ../sites-databases/drupal-project:/var/lib/mysql
    networks:
      - dockercompose
    command: mysqld --max_allowed_packet=64M
    restart: always
  drupal-project:
    container_name: drupal-project
    image: codekoalas/drupal8:permissionsFix
    environment:
      VIRTUAL_HOST: .drupal-project.localhost
      #GIT_HOSTS: "IP url" it was hard coded to our internal gitlab removed for safety
      GIT_REPO: https://github.com/fabean/drupal-project.git
      GIT_BRANCH: 8.x
      MYSQL_SERVER: mysql
      MYSQL_DATABASE: drupal
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      DRUPAL_BASE_URL: http://drupal-project.localhost
      DRUPAL_TRUSTED_HOSTS: drupal-project\.localhost$$
      DRUPAL_HTTPS: "off"
      APACHE_DOCROOT: /var/www/site/docroot
      PRODUCTION: "false"
      #SESMailHub: mail-relay.ckdev.io
      #LOCAL: "true"
    volumes:
      - ../sites-files/drupal-project:/mnt/site-files
      - ./:/var/www/site
      #- drupal-project-files-sync:/mnt/sites-files
      #- drupal-project-sync:/var/www/site
    networks:
      - dockercompose
    links:
      - drupal-project-mysql:mysql
    # extra_hosts:
      #- "xdebug:192.168.237.237"
    restart: always
networks:
  dockercompose:
    external:
      name: dockercompose_dockercompose
#volumes:
#  drupal-project-sync:
#    external: true
#  drupal-project-files-sync:
#    external: true
#  drupal-project-mysql-sync:
#    external: true
